"""audo incremnt 2

Revision ID: e12cdfa0cd9e
Revises: 60fb40b4b94b
Create Date: 2023-01-13 22:30:31.957005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12cdfa0cd9e'
down_revision = '60fb40b4b94b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
